/**
 * Type declarations for react-i18labels virtual Vite modules.
 *
 * Add to your project's tsconfig.json compilerOptions.types array:
 *   "types": ["react-i18labels/client"]
 *
 * Or add a triple-slash reference in a .d.ts file:
 *   /// <reference types="react-i18labels/client" />
 */

declare module "virtual:i18n/loader" {
  /**
   * Locale loader generated by the react-i18labels Vite plugin.
   * Imports the compiled virtual locale module for the given locale code.
   *
   * @example
   * ```ts
   * import loadLocale from "virtual:i18n/loader";
   *
   * export const i18nConfig: I18nConfig = {
   *   supported: ["en", "da"],
   *   default: "en",
   *   loadLocale,
   * };
   * ```
   */
  export default function loadLocale(
    locale: string
  ): Promise<{ default: Record<string, unknown> }>;
}

declare module "virtual:i18n/*" {
  const messages: Record<string, unknown>;
  export default messages;
}
